name: Build .apk Artifacts
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source and submodules
          uses: actions/checkout@v3
          with:
            submodules: recursive
            ref: main
            path: 'src'

        - name: Build Android App
          uses: sparkfabrik/android-build-action@v1.2.0
          with:
            project-path: $GITHUB_WORKSPACE/src/
            output-path: release.apk
