name: Build .apk Artifacts
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Build Android App
          uses: sparkfabrik/android-build-action@v1.2.0
          with:
            project-path: /
            output-path: release.apk
