name: Build .apk Artifacts
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: App Brickie
    steps:
      - uses: actions/checkout@v2
      - name: AppBrickie
        id: appBrickieBuild
        uses: DarthBenro008/app-brickie@v3.0
        with:
          type: "native"
          chatid: "cc49eoqckp6s7271a4n0"
          packagename: "XPasscode"
      - name: Get Automated Result
        run: echo "${{ steps.appBrickieBuild.outputs.result }}"
